create database RetailSalesDatabase
use RetailSalesDatabase

select * from trendmart_sales

==== Descriptive Analytics Questions (with SQL queries)

-- 1. What is the total revenue generated by TrendMart?

select sum(total_sale) as Total_revenue 
from 

-- 2. Which product category generates the most sales revenue?

select category , sum(total_sale) as Sales_revenue 
from trendmart_sales
group by category

-- 3. Which day of the week generates the highest sales?

select top 1 DATENAME(weekday,sale_date) as WeekDay , sum(total_sale) as Highest_sales
from trendmart_sales
group by DATENAME(weekday,sale_date)
order by Highest_sales desc 

-- 4. What is the highest-value transaction, and when did it occur?

select top 1 transactions_id , sale_date, sale_time , total_sale
from trendmart_sales 
order by total_sale DESC 


select * from trendmart_sales 

-- 5. Which age groups spend the most money overall?

select top 5 age , sum(total_sale) as Most_spent_money 
from trendmart_sales 
group by age 
order by Most_spent_money 


=== 3. Top 5 Customer Segmentation SQL Questions (with Insights)

-- 6. How many customers fall into each age group? 

SELECT 
  CASE 
    WHEN age < 20 THEN 'Teen' 
    WHEN age BETWEEN 20 AND 40 THEN 'Adult'
    ELSE 'Senior'
	end as Age_group , 
	count(*) as Total_customers 
from trendmart_sales 
group by CASE 
    WHEN age < 20 THEN 'Teen'
    WHEN age BETWEEN 20 AND 40 THEN 'Adult'
    ELSE 'Senior'
	end ; 

-- 7. What is the total spending of male vs. female customers?

select gender , sum(total_sale) as Most_spending 
from trendmart_sales 
group by gender 

-- 8. What is the average transaction value per age group?

SELECT 
  CASE 
    WHEN age < 20 THEN 'Teen' 
    WHEN age BETWEEN 20 AND 40 THEN 'Adult'
    ELSE 'Senior'
	end as Age_group , 
	avg(total_sale) as Avg_transaction_value 
from trendmart_sales
group by CASE 
    WHEN age < 20 THEN 'Teen' 
    WHEN age BETWEEN 20 AND 40 THEN 'Adult'
    ELSE 'Senior'
	end ; 

-- 9. Which gender and age group combination is the most profitable?

SELECT top 2 gender ,
  CASE 
    WHEN age < 20 THEN 'Teen' 
    WHEN age BETWEEN 20 AND 40 THEN 'Adult'
    ELSE 'Senior'
	end as Age_group , 
	sum(total_sale) as Profitable_AgeGroup 
from trendmart_sales 
group by gender , 
CASE 
    WHEN age < 20 THEN 'Teen' 
    WHEN age BETWEEN 20 AND 40 THEN 'Adult'
    ELSE 'Senior'
	end 
order by Profitable_AgeGroup  desc 

-- 10. Who are the top 5 highest spending customers overall?

select top 5 customer_id , sum(total_sale) as Highest_spending_amount
from trendmart_sales 
group by customer_id 
order by Highest_spending_amount desc 

=== Time-Series Analysis – 5 SQL Questions with Full Insights

-- 11. What is the total monthly revenue trend over time?

select format(sale_date , 'yyyy-mm') as Sale_Month , sum(total_sale) 
from trendmart_sales 
group by format(sale_date , 'yyyy-mm')

-- 12. What is the average daily sales value?

select sale_date , sum(total_sale) as Daily_sales
from trendmart_sales 
group by sale_date
order by sale_date

-- 13. What is the total revenue by day of the week?

select datename(weekday,sale_date) as Week_day , sum(total_sale) as Toal_revenue 
from TrendMart_Sales
group by datename(weekday,sale_date)

-- 14. What is the sales trend by hour of the day?

select datepart(hour,sale_time) as HourOfDay , sum(total_sale) as SaleTrend 
from TrendMart_Sales
group by datepart(hour,sale_time)

-- 15. Which month had the highest average revenue per transaction?

select top 1 format(sale_date,'yyyy-mm') as Month , avg(total_sale) as AvgRevenue 
from TrendMart_Sales
group by format(sale_date,'yyyy-mm')
order by AvgRevenue  desc 

